# Generated by Django 3.0 on 2021-05-08 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogcms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
    ]
