# Generated by Django 3.0 on 2021-05-08 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogcms', '0003_auto_20210508_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.GenericIPAddressField(default='0.0.0.0')),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='menu_item',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogcms.Category'),
        ),
        migrations.DeleteModel(
            name='Options',
        ),
        migrations.AddField(
            model_name='view',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogcms.Post'),
        ),
    ]
