# Generated by Django 3.0 on 2021-05-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogcms', '0005_auto_20210508_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='cover',
            field=models.BooleanField(default=False),
        ),
    ]
