# Generated by Django 3.0 on 2021-05-09 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogcms', '0007_auto_20210509_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogcms.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.BooleanField(default=False)),
                ('img', models.ImageField(upload_to='static/blogcms/img')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogcms.Post')),
            ],
        ),
        migrations.DeleteModel(
            name='PostData',
        ),
    ]
