# Generated by Django 3.0 on 2021-05-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogcms', '0008_auto_20210509_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
