# Generated by Django 3.0 on 2021-05-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogcms', '0009_auto_20210509_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
