# Generated by Django 3.0 on 2021-05-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogcms', '0011_auto_20210509_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
