# Generated by Django 3.0 on 2021-05-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogcms', '0012_image_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
