# Generated by Django 3.0 on 2021-05-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogcms', '0015_remove_post_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='page',
            field=models.BooleanField(default=False),
        ),
    ]
