# Generated by Django 3.0 on 2021-05-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogcms', '0017_auto_20210509_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
