# Generated by Django 3.0 on 2021-05-24 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogcms', '0020_auto_20210509_1802'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Embed',
        ),
    ]
